export const products = [
    {
        id: 1,
        name: 'Balcony Bageecha',
        price: 10000,
        description: "Hydroponics is growing plants without soil, using nutrient-rich water and Zero pesticides. Balcony Bageecha is a 100% Customizable hydroponics product allows you to farm in your balconies and rooftops. Hydroponics leads to faster plant growth, 90% water conservation compared to soil farming, minimum maintenance, maximum space utilization and soilless farming keeps your space clean and green.",
        category: ['farming'],
        type: ['outdoor'],
        img: "./balBag.PNG",
        slug: 'balcony-bageecha',
        colors: ['red', 'blue', 'green', 'yellow'],
    },
    // {
    //     id: 2,
    //     name: 'Vertical Farming',
    //     price: 13499,
    //     description: "Vertical farming is a method of growing crops vertically, maximizing space and resource efficiency while reducing water usage upto 90%, and eliminating the use of pesticides.",
    //     category: ['farming'],
    //     type: ['outdoor', 'indoor'],
    //     img: "https://imgs.search.brave.com/_u-baEXUmjX9ZDHQGA-hMapySexlRMt4STspCIRH2RA/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9yZXMu/Y2xvdWRpbmFyeS5j/b20vcGF0Y2gtZ2Fy/ZGVucy9pbWFnZS91/cGxvYWQvY19maWxs/LGhfMTAwMCxxX2F1/dG86Z29vZCx3XzEw/MDAvdjEvY21zL0Jh/bGNvbnkvMDMzQTY4/MjAtbWluLmpwZw",
    //     slug: 'vertical-farming',
    //     colors: [],
    // },
    {
        id: 3,
        name: 'Kalp-Taru: The Wish Tree',
        price: 13499,
        description: 'A patented product that allows you to grow plants vertically by conserving water and maximizing space efficiency. You can grow up to 42 plants within a square feet of area by using LED grow lights and aeroponic technology. Let your food be in your own hands and with zero pesticides, keep yourself and your family healthy. The aesthetic appeal of the product makes it not just a farming product but also one that can appeal to the audience in your living room.',
        category: ['farming'],
        type: ['indoor'],
        img: "./kalpTaruIndoor.PNG",
        slug: 'kalp-taru',
        colors: ['red', 'blue', 'brown', 'yellow'],
    },
    {
        id: 4,
        name: 'Kalp-Taru: The Wish Tree (Outdoor)',
        price: 6499,
        description: 'The outdoor version of Kalp-Taru. It can grow 42 plants however it comes without the LED grow lights and stand. This is ideal for your balconies and gardens.',
        category: ['farming'],
        type: ['outdoor'],
        img: "./kalpTaruOutdoor.PNG",
        slug: 'kalp-taru-outdoor',
        colors: [],
    },
    {
        id: 5,
        name: 'Indoor Mini Farm',
        price: 10000,
        description: 'Grow your favourite vegetables or ornamental plants indoors using LED lights and a vertical Farm stand. Available in multiple sizes and customizable.',
        category: ['farming'],
        type: ['indoor'],
        img: "./miniFarm.PNG",
        slug: 'indoor-mini-farm',
    },
    {
        id: 6,
        name: 'Outdoor Farm Stand',
        price: 7499,
        description: 'Built for the outdoors, plants use sunlight and nutrient rich water circulating in the system to grow. It comes in various sizes which can grow plants from anywhere between 20 to 100.',
        category: ['farming'],
        type: ['outdoor'],
        img: "./farmStand.PNG",
        slug: 'outdoor-farm-stand',
    },
    {
        id: 7,
        name: 'Indoor Vertical Farm By The Wall',
        price: 15000,
        description: 'Attached directly to walls, it grows crop via the nutrient film techniques (NFT) of Hydroponic farming. This design maximizes space efficiency, making it ideal for urban homes, offices, or small apartments. Equipped with builtin LED grow lights it provides an easy-to-maintain, sustainable way to cultivate herbs, vegetables, or ornamental plants indoors.',
        category: ['farming'],
        type: ['indoor'],
        img: "./verticalFarm.PNG",
        slug: 'indoor-vertical-farm',
    },
    {
        id: 8,
        name: 'Nature Samjyoti Lamp',
        price: 2199,
        description: 'This exquisite lamp showcases real preserved flowers delicately encased in a crystal-clear oil medium, radiating a soft, natural glow and propagating positivity. The base is adorned with authentic preserved moss, adding an earthy, organic touch to its design. Entirely sustainable and free from plastic, this lamp is a harmonious blend of elegance and eco-conscious craftsmanship.',
        category: ['gift', 'decor'],
        type: ['indoor'],
        img: "./samjyotiLamp.PNG",
        slug: 'nature-samjyoti-lamp',
    },
    {
        id: 9,
        name: 'Ishwar Samjyoti Lamp',
        price: 2499,
        description: 'This unique lamp showcases a serene God idol surrounded by real preserved flowers embedded in an oil medium, radiating warmth and positivity when lit. The base, covered in real preserved moss, evokes a natural, tranquil environment, harmoniously blending spirituality and nature. Designed to inspire a positive connection with the environment, this sustainable creation avoids plastic, serving as a reminder of the divine presence in nature and encouraging mindful behavior toward the planet.',
        category: ['gift', 'decor'],
        type: ['indoor'],
        img: "./ishwarLamp.PNG",
        slug: 'ishwar-samjyoti-lamp',
    },
    {
        id: 10,
        name: 'Bamboo Shakti',
        price: 1499,
        description: 'Enhance your walls with our stunning handmade bamboo god idol wall hanging, illuminated by light propagating a divine glow. Surrounded by real preserved moss, this unique decor piece blends devotion with nature inspiring a positive change in preserving the environment.',
        category: ['decor'],
        type: ['indoor', 'outdoor'],
        img: "./bambooShakti.PNG",
        slug: 'bamboo-shakti',
    },
    {
        id: 11,
        name: 'Green Mirror',
        price: 1499,
        description: 'Bring nature indoors with our circular mirror, elegantly bordered with real moss and preserved plants. This product combines functionality with nature, creating a refreshing and eco-friendly statement for your space. Perfect for adding a touch of greenery to any room, it offers a blend of modern design and natural charm.',
        category: ['decor'],
        type: ['indoor'],
        img: "./greenMirror.PNG",
        slug: 'green-mirror',
    },
    {
        id: 12,
        name: 'Prakriti Glow Spotlight',
        price: 4999,
        description: 'Prakriti Glow combines nature and functionality, featuring live plants arranged vertically at the sides for a vibrant, eco-friendly touch illuminated by 2 spotlights. It includes a lamp crafted with real preserved flowers encased in a bamboo lid and glass jar, emitting a warm glow, and a tempered glass shelf designed to hold decor or utility items. A spotlight at the top enhances the illumination, highlighting the lamp, plants, and items on the shelf, creating a stunning and eco-conscious centerpiece.',
        category: ['decor'],
        type: ['indoor'],
        img: "./prakritiSpotlight.PNG",
        slug: 'prakriti-glow-spotlight',
    },
    {
        id: 13,
        name: 'Prakriti Glow Striplight',
        price: 4499,
        description: 'A variant of Prakrit Glow where instead of spotlights to illuminate plants, LED striplight has been used created a more linear look.',
        category: ['decor'],
        type: ['indoor'],
        img: "./prakritiStriplight.PNG",
        slug: 'prakriti-glow-striplight',
    },
    {
        id: 14,
        name: 'Prakriti Book Shelf',
        price: 3799,
        description: 'This innovative bookshelf integrates live plants vertically within its design, combining storage with greenery to promote sustainable living. Crafted from eco-friendly materials, it enhances air quality while serving as a functional and stylish centerpiece for any space.',
        category: ['decor'],
        type: ['indoor'],
        img: "./prakritiShelf.PNG",
        slug: 'prakriti-book-shelf',
    },
    {
        id: 15,
        name: 'Moss Frames',
        price: 3499,
        description: 'This customizable product features real preserved moss and other natural plants, bringing a touch of greenery and serenity to any indoor space. Available in a variety of sizes, it is designed to seamlessly fit different interiors while requiring no maintenance. The addition of an LED border enhances its aesthetic appeal, creating a striking blend of nature and modern design.',
        category: ['decor'],
        type: ['indoor'],
        img: "./mossFrame.PNG",
        slug: 'moss-frames',
    },
    {
        id: 16,
        name: 'Vayu Pure',
        price: 0,
        description: 'This innovative air purifier combines advanced mechanical carbon filters with the natural power of plant roots through phytoremediation to cleanse the air of pollutants effectively. With an elegant design housing 10 live plants, it seamlessly integrates technology and nature, offering both functionality and aesthetic appeal for healthier indoor environments.',
        category: ['nbs'],
        type: ['indoor'],
        img: "./vayuPure.PNG",
        slug: 'vayu-pure',
    },
    {
        id: 17,
        name: 'Vriksha-Wall',
        price: 0,
        description: 'A living wall system, a vertical structure featuring live plants securely attached to a wall, supported by an automated irrigation and nutrient delivery system. This product can be customized according to the needs of the clients in a comprehensive manner.',
        category: ['nbs'],
        type: ['indoor', 'outdoor'],
        img: "./vrikshaWall.PNG",
        slug: 'vriksha-wall',
    },
    
]